---

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Add nodejs from Nodesource"
  become: true
  shell: |
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl gnupg
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    NODE_MAJOR=16
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    
    sudo apt-get update
    sudo apt-get install nodejs -y

    # curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "Install Nodejs"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: true
  npm:
    name: n
    global: yes
    production: yes
  

- name: "install PM2 Globally"
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present

