---
  - name: Copy files
    become: true
    copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
  - name: Unarchive
    become: true
    shell : |
        cd /home/ubuntu/
        tar xvzf artifact.tar.gz -C .

  - name: "run server"
    become: true
    shell : |
        cd /home/ubuntu/
        npm install
        pm2 stop default
        pm2 start npm -- start

  # - name: extract artifact
  #   become: true
  #   unarchive:
  #     src: files/artifact.tar.gz
  #     dest: .

  # - name: "Create backend app directory"
  #   file:
  #     path: ~/backend-app
  #     state: directory

  # - name: "Unarchive backend files"
  #   become: true
  #   unarchive:
  #     src: files/artifact.tar.gz
  #     dest: ~/backend-app
  
  # - name: "Installing Node Dependencies"
  #   shell: |
  #     cd ~/backend-app
  #     echo PWD
  #     # npm install
  
  # - name: "Executing Node app with PM2"
  #   shell: |
  #     cd ~/backend-app/dist
  #     pm2 stop default
  #     pm2 start main.js
    
  #   register: execute_code

  # - name: print_message
  #   debug:
  #     msg: "{{ execute_code.stdout_lines }}"

  # - name: "Configure pm2 to start as a service"
  #   become: true
  #   shell: |
  #     env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp  /home/ubuntu

